---
global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'dev-prometheus'

scrape_config_files:
  - /etc/prometheus/scrapes/*.yml

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['node-exporter:9100']
