---
apiVersion: 1

deleteDatasources:
  - name: Loki
    orgId: 1

datasources:
  - name: Loki
    type: loki
    orgId: 1
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000
    editable: true
  - name: Prometheus
    type: prometheus
    orgId: 1
    url: http://prometheus:9090
    editable: true
    version: 1
